### ISSUE TITLE
to_paf.py is very slow

### ISSUE THREAD

**Issue by gsc74** [milkschen/chaintools#10]
@milkschen and @nhansen, I'm using the following command to generate `liftover-split.paf`

```
python3 chaintools/src/chaintools/to_paf.py -c liftover-split.chain -t ../CHM13Y_L.fa -q ../GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta -o liftover-split.paf
```

It seems that generating `*.paf` from `to_paf.py` is very slow. What is the alternate way to speed up the computation? And what is the estimated time for whole genome human references?

**Comment by gsc74** [comment]
> @milkschen and @nhansen, I'm using the following command to generate `liftover-split.paf`
> 
> ```
> python3 chaintools/src/chaintools/to_paf.py -c liftover-split.chain -t ../CHM13Y_L.fa -q ../GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta -o liftover-split.paf
> ```
> 
> It seems that generating `*.paf` from `to_paf.py` is very slow. What is the alternate way to speed up the computation? And what is the estimated time for whole genome human references?

Target and query sequences were interchanged, and that was the issue.

**Comment by milkschen** [comment]
Hi @gsc74, Thanks for sharing the experience!
